Changes since 2.6.16.27:
Adrian Bunk:
      fix the SND_FM801_TEA575X dependencies
      SOUND_SSCAPE shouldn't depend on OBSOLETE_OSS_DRIVER
      update the i386 defconfig
      Linux 2.6.16.28-rc1
      Linux 2.6.16.28-rc2
      Linux 2.6.16.28-rc3
      Linux 2.6.16.28

Al Boldi:
      ide-io: increase timeout value to allow for slave wakeup

Andi Kleen:
      BLOCK: Fix bounce limit address check

Bob Breuer:
      SPARC32: Fix iommu_flush_iotlb end address

Chuck Ebbert:
      ieee80211: TKIP requires CRC32

Danny Tholen:
      1394: fix for recently added firewire patch that breaks things on ppc

Dave Jones:
      [AGPGART] Fix Nforce3 suspend on amd64.

David S. Miller:
      SPARC64: Fix quad-float multiply emulation.

Jan Kara:
      Fix possible UDF deadlock and memory corruption (CVE-2006-4145)

Jens Axboe:
      Fix missing ret assignment in __bio_map_user() error path
      fix debugfs inode leak
      cdrom: fix bad cgc.buflen assignment (CVE-2006-2935)

Michael S. Tsirkin:
      IB/mthca: restore missing PCI registers after reset

Olof Johansson:
      powerpc: Clear HID0 attention enable on PPC970 at boot time (CVE-2006-4093)

Pavel Machek:
      remove obsolete swsusp_encrypt
      pdflush: handle resume wakeups

Robert Hancock:
      Fix broken suspend/resume in ohci1394

Sridhar Samudrala:
      Fix sctp privilege elevation (CVE-2006-3745)

Stefan Richter:
      ieee1394: sbp2: enable auto spin-up for Maxtor disks

Yasunori Goto:
      memory hotplug: solve config broken: undefined reference to `online_page'