Merge from devel/programming/languages/python/django/Django/:
rev. 77204, by caglar on 2009-09-19
AttributeError at /admin/comments/comment/add/

'Comment' object has no attribute 'get_content_object'

Request Method: 	POST
Request URL: 	http://localhost:8080/admin/comments/comment/add/
Exception Type: 	AttributeError
Exception Value: 	

'Comment' object has no attribute 'get_content_object'

Exception Location: 	/usr/lib/python2.5/site-packages/django/contrib/comments/models.py in save, line 85
Python Executable: 	/usr/bin/python

rev. 77208, by caglar on 2009-09-19
according to Django docs, comments module already provides this

rev. 78093, by erenturkay on 2009-10-11
Fix denial of service vulnerability caused by regular expression module

BUG:COMMENT:11322